name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use the version that suits your project

      - name: Install dependencies
        run: npm install

      - name: Deploy to Firebase
        uses: wzieba/Firebase-Hosting-Action@v2.1.0
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: your-project-id
